### ISSUE TITLE
Refresh button or callback function for refresh

### ISSUE THREAD

**Issue by Yetispapa** [AmrSaied/hive_ui#1]
Hi there,

First of all, thanks for this great package 🎉 I implemented kind of a split view of my running app and a database previewer with your package, which works great. Except one thing, I have to go back and forth to refresh the UI, when the database has been changed.

Maybe worth to mentioned, I use your package mainly, to have a UI to check if my Hive database has the state, what I expect. As an example, if I edit my user, is all the data correct modified in the database. As its cool to have the action buttons like copy, delete etc., I don't really use them.

Do you think, its possible to have a refresh button somewhere, which reinitialized the page or even better, something like a callback which triggers the refresh, as I could build something by my own with the stream functionality, which Hive offers. If this would be possible, I can check via the database split view, on the fly if my database is correct.

This would be awesome!

**Comment by AmrSaied** [comment]
Thanks for you support working on it and will fix I next version

**Comment by AmrSaied** [comment]
Fix in version hive_ui 1.0.14  by added refresh button
